version: '3.8'

services:
  finally:
    build:
      context: .
      dockerfile: Dockerfile
    image: finally:latest
    container_name: finally
    ports:
      - "8000:8000"
    volumes:
      - ./db:/app/db
    env_file:
      - .env
    restart: unless-stopped
