import { test, expect } from '@playwright/test';

const API_BASE = 'http://localhost:4000/api';

// Run tests serially since they share backend state
test.describe.configure({ mode: 'serial' });

// Helper to log in before reaching the board
async function loginAndWait(page: import('@playwright/test').Page) {
  await page.goto('/');
  // Click the Sign In button (dummy login, no credentials needed)
  const submitBtn = page.locator('[data-testid="login-submit"]');
  await expect(submitBtn).toBeVisible();
  await submitBtn.click();

  // Wait for the board to render
  await expect(page.locator('[data-testid="kanban-board-grid"]')).toBeVisible({ timeout: 10000 });
  await page.waitForTimeout(500);
}

test.describe('Kanban Application Integration Flow', () => {
  test.beforeEach(async ({ page }) => {
    // Reset backend database to pristine seed state
    await fetch(`${API_BASE}/reset`, { method: 'POST' });
    await loginAndWait(page);
  });

  test('displays application header and 5 default columns', async ({ page }) => {
    await expect(page.locator('h1')).toContainText('Kanban Project Manager');

    const columns = page.locator('[data-testid="kanban-column"]');
    await expect(columns).toHaveCount(5);

    await expect(page.locator('[data-testid="column-title-col-1"]')).toContainText('Backlog');
    await expect(page.locator('[data-testid="column-title-col-2"]')).toContainText('To Do');
    await expect(page.locator('[data-testid="column-title-col-3"]')).toContainText('In Progress');
    await expect(page.locator('[data-testid="column-title-col-4"]')).toContainText('In Review');
    await expect(page.locator('[data-testid="column-title-col-5"]')).toContainText('Done');
  });

  test('allows inline column title renaming', async ({ page }) => {
    const columnHeader = page.locator('[data-testid="column-title-col-1"]');
    await columnHeader.click();

    const input = page.locator('[data-testid="column-rename-input-col-1"]');
    await expect(input).toBeVisible();

    await input.fill('Idea Pool');
    await input.press('Enter');

    await expect(page.locator('[data-testid="column-title-col-1"]')).toContainText('Idea Pool');
  });

  test('supports adding a new card', async ({ page }) => {
    await page.locator('[data-testid="add-card-btn-col-1"]').click();

    const titleInput = page.locator('[data-testid="card-title-input"]');
    const detailsInput = page.locator('[data-testid="card-details-input"]');
    const submitBtn = page.locator('[data-testid="submit-card-btn"]');

    await titleInput.fill('Playwright Automated Card');
    await detailsInput.fill('Generated by end-to-end integration test suite.');
    await submitBtn.click();

    await expect(page.locator('text=Playwright Automated Card').first()).toBeVisible();
  });

  test('supports deleting a card', async ({ page }) => {
    const targetCard = page.locator('[data-card-id="card-1"]');
    await expect(targetCard).toBeVisible();

    await targetCard.hover();
    const deleteBtn = targetCard.locator('[data-testid="delete-card-card-1"]');
    await deleteBtn.click();

    await expect(page.locator('[data-card-id="card-1"]')).not.toBeVisible();
  });
});
